### ISSUE TITLE
Replace GitHub Actions references with hashes

### ISSUE THREAD

**Issue by lpsinger** [nasa-gcn/gcn.nasa.gov#2961]
# Description

There was recently a high-profile [GitHub Actions supply chain compromise](https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-tj-actionschanged-files-cve-2025-30066-and-reviewdogaction).

Current best practice is to use commit hashes rather than version numbers when linking to GitHub Actions from the marketplace. Instead of this:

```yaml
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
```

use this:

```yaml
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
```

# Acceptance criteria

Update all projects to use git hashes in workflow references.

# Notes

The Python package [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) can read and write yaml files and preserves comments. This will be useful for automating the migration.
